---
title: "ANLY 500 Final Project"
author: "Mithil Kashyap Vyas"
date: "4/15/2022"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#### SETTING PATH ####
setwd("C:\\Users\\mithi\\Documents\\anly500\\project\\data\\sample")

#### INSTALLING PACKAGE ####
library(stringr)
library(RSQLite)
library(rvest)
library(plyr)


#### LISTING ALL THE FILES HAVING .DAT FORMAT ####
filelist1 = list.files(pattern = ".*.dat")
```


```{r}
#### READING THE DATA AND CREATING DATAFRAME ####
q <- as.numeric()
for( j in 1:length(filelist1))
{
  myfile <- readLines(filelist1[j])
  p <- grep("<URL>",myfile)
  if(length(p)==0){q <- append(q,j)
  }
}
filelist <- filelist1[-q]

main_frame <- data.frame(Hotel=character(),City=character(),State=character(),OverallRating=numeric(),Overall=numeric(),Cleanliness=numeric(),Rooms=numeric(),
                         Value=numeric(),Service=numeric(),Location=numeric(),Cf=numeric(),Bs=numeric(),
                         Price=character(),stringsAsFactors = FALSE)
```


```{r}
#### RUNNING A LOOP FOR ALL THE PARAMETERS OF THE DATASET AND CALCULATING MEAN FOR MULTIPLE PARAMETERS ####
for(i in 1 : length(filelist))
{
  myfile <- readLines(filelist[i])                                #reading all the files line by line
  overall_rating <- myfile[grep("<Overall Rating>", myfile)]      #matching tags <Overall Rating>
  count_overall_no <- as.numeric(gsub(".*>", "", overall_rating)) #counting tag <Overall Rating>
  
  overall <- myfile[grep("<Overall>", myfile)]                    #matching tags <Overall>
  count_overall <- as.numeric(gsub(".*>", "", overall))           #counting tag <Overall>
  overall_no <- round(mean(count_overall),digits = 0)
  
  cleanliness <- myfile[grep("<Cleanliness>", myfile)]            #matching tags <Cleanliness>
  count_cleanliness <- gsub("-1", count_overall_no, cleanliness)  #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  cleanliness_all <- as.numeric(gsub(".*>", "", count_cleanliness))#counting tag <Overall>
  cleanliness_no <- round(mean(cleanliness_all),digits = 0) 
  
  rooms <- myfile[grep("<Rooms>", myfile)]                        #matching tags <Rooms>
  count_rooms <- gsub("-1", count_overall_no, rooms)              #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  rooms_all <- as.numeric(gsub(".*>", "", count_rooms))           #counting tag <Rooms>
  rooms_no <- round(mean(rooms_all),digits = 0)                   #putting count in the data-frame rooms_df
  
  value <- myfile[grep("<Value>", myfile)]                        #matching tags <Value>
  count_value <- gsub("-1", count_overall_no, value)              #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  value_all <- as.numeric(gsub(".*>", "", count_value))           #counting tag <Value>
  value_no <- round(mean(value_all),digits = 0)                   #putting count in the data-frame value_df
  
  service <- myfile[grep("<Service>", myfile)]                    #matching tags <Service>
  count_service <- gsub("-1", count_overall_no, service)          #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  service_all <- as.numeric(gsub(".*>", "", count_service))       #counting tag <Service>
  service_no <- round(mean(service_all),digits = 0)               #putting count in the data-frame service_df
  
  location <- myfile[grep("<Location>", myfile)]                  #matching tags <Location>
  count_location <- gsub("-1", count_overall_no, location)        #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  location_all <- as.numeric(gsub(".*>", "", count_location))     #counting tag <Location>
  location_no <- round(mean(location_all),digits = 0)             #putting count in the data-frame location_df
  
  cf <- myfile[grep("<Check in / front desk>", myfile)]           #matching tags <Check in / front desk>
  count_cf <- gsub("-1", count_overall_no, cf)                    #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  cf_all <- as.numeric(gsub(".*>", "", count_cf))                 #counting tag <Check in / front desk>                   
  cf_no <- round(mean(cf_all),digits = 0)                         #putting count in the data-frame cf_df
  
  bs <- myfile[grep("<Business service>", myfile)]                #matching tags <Business service>
  count_bs <- gsub("-1", count_overall_no, bs)                    #replacing the -1  rating values by the overall rating from the  count_overall_rating_df
  bs_all <- as.numeric(gsub(".*>", "", count_bs))                 #counting tag <Business service>   
  bs_no <- round(mean(bs_all),digits = 0)                         #putting count in the data-frame bs_df
  
  price <- myfile[grep("<Avg. Price>", myfile)]                   #matching tags <Overall>
  count_price <-gsub(".*>", "", price)                            #counting tag <Overall>
  price_no <- count_price                                         #putting count in the data-frame overall_df
 
#### EXTRACTING THE CITY AND STATE NAME #### 
  y <- grep("<URL>",myfile)                                       
  z <- gsub(".html","",myfile[y])
  a1 <- data.frame(str_split_fixed(z,"\\d{8}-",2),stringsAsFactors = FALSE)
  colnames(a1) <- c("A","B")
  a2 <- data.frame(str_split_fixed(a1$B,"-",2),stringsAsFactors = FALSE)
  colnames(a2) <- c("HotelName","CityState")
  Hotel <- gsub("_"," ",a2$HotelName)
  str_match(a2$CityState, "(.*?)_([^_]+)$")
  city <- str_match(a2$CityState, "(.*?)_([^_]+)$")[, 2]
  state <- str_match(a2$CityState, "(.*?)_([^_]+)$")[, 3]
  a3 <- data.frame(city,state,stringsAsFactors = FALSE)
  colnames(a3) <- c("City","State")
  #a3$City
  #a3$State
  
  main_frame <- rbind(main_frame,data.frame(Hotel,a3$City,a3$State,count_overall_no,overall_no,cleanliness_no,
                                            rooms_no,value_no,service_no,location_no,cf_no,bs_no,price_no,
                                            stringsAsFactors = FALSE))
}

colnames(main_frame) <- c("Hotel","City","State","Overall_Count","Overall","Cleanliness","Rooms","Value",
                          "Service","Location","CF","BS","Price")

#### REPLACING THE EMPTY CELLS WITH NA AND THEN REMOVING NA FROM THE DATAFRAME ####
main_frame[main_frame==""]<-NA
main_frame<-na.omit(main_frame)

#### EXTRACTING NEWYORK SEPARATELY AS THIS IS A SPECIAL CASE IN THE FILE ####
main_frame$City <-gsub("_"," ",main_frame$City)
main_frame$City[main_frame$State == 'York'] <- 'New York City'
main_frame$State[main_frame$State == 'York'] <- 'New York'
```


```{r}
#### REPLACING UNKNOWN IN PRICE COLUMN WITH NA ####

main<-main_frame$Price[main_frame$Price=="Unkonwn"]<-NA
#main<-na.omit(main)

#main_frame$Price[98]
##main_frame$Price[main_frame$Price=="Unknown"]<-NA

################################### DB Connection code####################################

#### FORMING A CONNECTION WITH THE DATABASE ####

db <- dbConnect(SQLite(), dbname="Tripadvisor.sqlite")


##### Queries for creating tables ####
dbRemoveTable(db, "city")
dbRemoveTable(db, "state")
dbRemoveTable(db, "HotelRating")


dbSendQuery(db,  "CREATE TABLE state (
            state_ID INTEGER PRIMARY KEY,
            stateName TEXT)")

dbSendQuery(db,  "CREATE TABLE city (
            city_ID INTEGER PRIMARY KEY,
            cityName TEXT)")

dbSendQuery(db,  "CREATE TABLE HotelRating (
            HotelID INTEGER PRIMARY KEY,
            HotelName Text,
             city_ID Integer,
            state_ID Integer,
            cleanliness integer,
            rooms_rating integer,
            value_rating integer,
            service_rating integer,
            location_rating integer,
            CF_rating integer,
            BS_rating integer,
            price double,
            overall_rating integer,
            Foreign key(city_ID) references city(city_ID),
            Foreign key(state_ID) references state(state_ID)
          )")



#### CREATING CITYDATA FROM Tripadvisor.sqlite CONTAINING DATA FOR CITYDATA ####
cityData <- unique(cbind.data.frame(main_frame$City))
cityData <-(cbind.data.frame(1:nrow(cityData),cityData))
colnames(cityData) <- c("city_ID","cityName")
dbWriteTable(conn = db, name = "city",value = cityData,append = TRUE)


#### CREATING STATEDATA FROM Tripadvisor.sqlite CONTAINING DATA FOR STATEDATA ####
stateData <- unique(cbind.data.frame(main_frame$State))
stateData <-(cbind.data.frame(1:nrow(stateData),stateData))
colnames(stateData) <- c("state_ID","stateName")
dbWriteTable(conn = db, name = "state",value = stateData,append = TRUE)


# MERGING THE CITYDATA AND STATEDATA 
merge.data <- merge(main_frame,cityData,by.x =c("City"),by.y = c("cityName"))
merge.data <- merge(merge.data,stateData,by.x =c("State"),by.y = c("stateName"))
rm('ratingData')
ratingData <- unique(cbind.data.frame(merge.data$Hotel,
                                      merge.data$city_ID,
                                      merge.data$state_ID,
                                      merge.data$Cleanliness,
                                      merge.data$Rooms,
                                      merge.data$Value,
                                      merge.data$Service,
                                      merge.data$Location,
                                      merge.data$CF,
                                      merge.data$BS,
                                      merge.data$Price,
                                      merge.data$Overall))
ratingData <-(cbind.data.frame(1:nrow(ratingData),ratingData))
colnames(ratingData) <- c('HotelID' , 'HotelName' , 'city_ID' ,'state_ID' ,'cleanliness','rooms_rating' ,'value_rating',
                          'service_rating','location_rating' , 'CF_rating', 
                          'BS_rating', 'price' ,'overall_rating')
dbWriteTable(conn = db, name = "HotelRating",value = ratingData,append = TRUE)
dbReadTable(db,'HotelRating')



#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE RATING IS FOUR OR GREATER THAN FOUR #### 
rating_higher <- dbGetQuery(db,"select HotelName,price,overall_rating from HotelRating where overall_rating >='4'");
rating_higher


#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE CLEANLINESS RATING IS FOUR OR GREATER THAN FOUR #### 
cleanliness_higher <- dbGetQuery(db,"select HotelName,price,cleanliness from HotelRating where cleanliness >='4'");
cleanliness_higher


#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE ROOMS RATING IS FOUR OR GREATER THAN FOUR #### 
rooms_higher <- dbGetQuery(db,"select HotelName,price,rooms_rating from HotelRating where rooms_rating >='4'");
rooms_higher

#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE VALUE RATING IS FOUR OR GREATER THAN FOUR ####
value_higher <- dbGetQuery(db,"select HotelName,price,value_rating from HotelRating where value_rating >='4'");
value_higher


#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE SERVICE RATING IS FOUR OR GREATER THAN FOUR ####
Service_higher <- dbGetQuery(db,"select HotelName,price,service_rating from HotelRating where service_rating >='4'");
Service_higher

#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE LOCATION RATING IS FOUR OR GREATER THAN FOUR ####
location_higher <- dbGetQuery(db,"select HotelName,price,location_rating from HotelRating where location_rating >='4'");
location_higher

#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE CF RATING IS FOUR OR GREATER THAN FOUR ####
cf_higher <- dbGetQuery(db,"select HotelName,price,cf_rating from HotelRating where cf_rating >='4'");
cf_higher

#### QUERY TO RETREIVE THE HOTEL NAME AND ITS PRICE FOR WHICH THE CF RATING IS FOUR OR GREATER THAN FOUR ####
bs_higher <- dbGetQuery(db,"select HotelName,price,bs_rating from HotelRating where bs_rating >='4'");
bs_higher



################################# ANALYSIS ######################################



#### FINDING THE CORRELATION OF OVERALL_COUNT WITH THE REST OF THE PARAMETERS ####

cleanlinesscorr<-cor.test(main_frame$Overall_Count,main_frame$Cleanliness)
Roomscorr<-cor.test(main_frame$Overall_Count,main_frame$Rooms)
Valuecorr<-cor.test(main_frame$Overall_Count,main_frame$Value)
Servicecorr<-cor.test(main_frame$Overall_Count,main_frame$Service)
Locationcorr<-cor.test(main_frame$Overall_Count,main_frame$Location)
CFcorr<-cor.test(main_frame$Overall_Count,main_frame$CF)
BScorr<-cor.test(main_frame$Overall_Count,main_frame$BS)
```


Analyzing the data

```{r}
library(tidyverse)
data = main_frame
#dropping all records with missing values
data = data %>% drop_na()

#converting currency to dollars
data$Price <- as.numeric(gsub('[$,]', '', data$Price))
summary(data)

# the column: Overall is the overall rating of the hotel based on various factors like  Room_Rating, Location_Rating, Cleanliness_Rating, Check_in/front_desk_Rating,	Service_Rating,	Business_Service_Rating. The ratings start at 1-5, 1 being the lowest and 5 being the highest reviews.
```


```{r}
print(table(data$Overall))

barplot(table(data$Overall),main="Tripadvisor Hotel Reviews",xlab="Overall Reviews (1-5)")
```


```{r}
plot(data$Cleanliness ~ data$Overall)
plot(data$Rooms ~ data$Overall)
plot(data$Value ~ data$Overall)
plot(data$Service ~ data$Overall)
plot(data$Location ~ data$Overall)
plot(data$CF ~ data$Overall)
plot(data$BS ~ data$Overall)
plot(data$Price ~ data$Overall)
```





```{r}
boxplot(data$Cleanliness ~ data$Overall)
boxplot(data$Rooms ~ data$Overall)
boxplot(data$Value ~ data$Overall)
boxplot(data$Service ~ data$Overall)
boxplot(data$Location ~ data$Overall)
boxplot(data$CF ~ data$Overall)
boxplot(data$BS ~ data$Overall)
boxplot(data$Price ~ data$Overall)
```



```{r density_plotting}
hist(data$Cleanliness)
plot(density(data$Cleanliness))

hist(data$Rooms)
plot(density(data$Rooms))

hist(data$Value)
plot(density(data$Value))

hist(data$Service)
plot(density(data$Service))

hist(data$Location)
plot(density(data$Location))

hist(data$CF)
plot(density(data$CF))

hist(data$BS)
plot(density(data$BS))

hist(data$Price)
plot(density(data$Price))
```


```{r data_correlation}

need_Data=data[c("Cleanliness", "Rooms", "Value", "Service", "Location","CF", "BS", "Price")]

names(need_Data)

library(corrplot)
corrplot(cor(need_Data))

cor(need_Data)^2

plot(need_Data)

library(ppcor)
## Loading required package: MASS
pcor(need_Data)
spcor(need_Data)

```


```{r}
#data$Cleanliness 
#data$Rooms 
#data$Value 
#data$Service 
#data$Location 
#data$CF
#data$BS
#data$Price
```

```{r data_confidence_interval}

t.test(data$Cleanliness) 
t.test(data$Rooms)
t.test(data$Value)
t.test(data$Service) 
t.test(data$Location)
t.test(data$CF)
t.test(data$BS)
t.test(data$Price)
```

```{r chisquare_test}
result = chisq.test(data$Cleanliness, data$Overall)
print(result)

result = chisq.test(data$Rooms, data$Overall)
print(result)

result = chisq.test(data$Value, data$Overall)
print(result)

result = chisq.test(data$Service, data$Overall)
print(result)

result = chisq.test(data$Location, data$Overall)
print(result)


result = chisq.test(data$CF, data$Overall)
print(result)


result = chisq.test(data$BS, data$Overall)
print(result)

result = chisq.test(data$Price, data$Overall)
print(result)


```


Outlier analysis

```{r outliers}
mahal_scores = mahalanobis(x=data[, 6:13], 
                           center = colMeans(data[, 6:13]), 
                           cov = cov(data[, 6:13], 
                                     use = "pairwise.complete.obs")
                           )
# Summary of all mahal scores
summary(mahal_scores)

# For this analysis, let's use alpha of 0.001 for determining outlier. Since Mahalanobis distance follows chi-squared distribution, let's compute cutoff using chi-squared table. There are 8 numerical variables in the dataframe for the outlier analysis and hence degrees of freedom (df) is 8.
cutoff_value = qchisq(p = 1 - 0.001, df = 8)
cutoff_value

# Identify scores that are not below the threshold
summary(mahal_scores < cutoff_value)
# Based on Mahalanobis distance, there are 46 outliers in dataset

# Let's eliminate the outliers based on threshold
post_outlier_screen_data = subset(data, mahal_scores < cutoff_value)
```



